#! /bin/sh

bspc config border_width        5
bspc config window_gap         12

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config click_to_focus      true

bspc monitor DVI-I-2 -d web vid work
bspc monitor DVI-I-3 -d term chat steam

bspc rule -a mpv state=floating
bspc rule -a steam desktop=^6
bspc rule -a feh state=floating
bspc rule -a imv state=floating
bspc rule -a Firefox desktop='^1'
bspc rule -a Deluge desktop=^3

bspc desktop -f term 
urxvt &

panel &
