#! /bin/sh

bspc config border_width        5
bspc config window_gap         12

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor DVI-I-2 -d web vid work
bspc monitor DVI-I-3 -d term chat steam

bspc rule -a mpv floating=on
bspc rule -a steam desktop=^6
bspc rule -a feh floating=on
bspc rule -a imv floating=on
bspc rule -a sxiv floating=on
bspc rule -a firefox desktop=^1

bspc desktop -f term 
urxvt &

panel &
